[package]
name = "lettuce"
version = "0.1.0"
authors = ["Denny Rommel <rommel.denny@gmail.com>"]
edition = "2024"
description = "Terminal emulator"
license = "MIT"

[dependencies]
anyhow = "1.0"
portable-pty = "0.9.0"
